### ISSUE TITLE
To Do List // What to learn

### ISSUE THREAD

**Issue by muriloxyz** [muriloxyz/dataset-split#1]
Well, I need to understand some crucial stuff before building this app.

### Tasks : 
- [x] Collect initial path (ipath)
- [x] Find the best way to collect desired ratio for splitting the data
- [x] List all classes (subdirs) in ipath
- [x] Create (train - validation - test) folders
- [x] Create all classes inside train-val-test directories
- [x] Iterate over each original class and:
    * [x] Calculate how many items there's inside
    * [x] Calculate the splits
    * [x] **RANDOMLY** move the desired amount of items to test-val-test  correct subdirs
- [x] Delete original class directories (empty)
---
- [ ] **Think of improvements**
    * [ ] List them here
---
- [x] Setup CI
- [x] Publish on PyPi 

---
- [ ] **Finished**

---

What I need/must understand in order to build this app:
- [x] How to manipulate paths the right way
- [x] How to list in a given path
- [x] Create directories
- [x] Move files
- [x] Delete files
- [x] Calculate splits for all amounts of data
- [x] Decent randomness
